// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omtcdftgznbrxfcwzmwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdGNkZnRnem5icnhmY3d6bXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzMzNDYsImV4cCI6MjA2MzY0OTM0Nn0.AiVnAYbMITPALkhVM_UdOoAdf6S_uhRyIolQacAD8Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);